version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  reviewers:
  - AdamVig
  versioning-strategy: widen
  ignore:
  - dependency-name: eslint
    versions:
    - 7.19.0
